import Foundation

enum MissionWorkspaceCopy {
    static func text(_ key: String, language: String) -> String {
        let index = ["en": 0, "nl": 1, "de": 2, "fr": 3, "es": 4][language] ?? 0
        let rows: [String: [String]] = [
            "statusFilter": ["Status", "Status", "Status", "État", "Estado"],
            "allStatuses": ["All statuses", "Alle statussen", "Alle Zustände", "Tous les états", "Todos los estados"],
            "USER": ["You", "Jij", "Sie", "Vous", "Tú"],
            "BUSINESS": ["Business", "Business", "Business", "Business", "Negocio"],
            "ARCHITECTURE": ["Architect", "Architect", "Architekt", "Architecte", "Arquitecto"],
            "Research": ["Research", "Onderzoek", "Untersuchung", "Recherche", "Investigación"],
            "objective": ["Goal", "Doel", "Ziel", "Objectif", "Objetivo"],
            "architectureChoices": ["Design choices", "Ontwerpkeuzes", "Entwurfsentscheidungen", "Choix de conception", "Decisiones de diseño"],
            "consequences": ["What approval allows", "Wat goedkeuring toestaat", "Was die Genehmigung erlaubt", "Ce que l’approbation permet", "Qué permite la aprobación"],
            "risks": ["Risks to consider", "Risico’s om te beoordelen", "Zu beurteilende Risiken", "Risques à évaluer", "Riesgos a evaluar"],
            "remainingDecisions": ["Remaining human decisions", "Resterende menselijke beslissingen", "Verbleibende menschliche Entscheidungen", "Décisions humaines restantes", "Decisiones humanas pendientes"],
            "notEstablished": ["Not established yet; clarify in the conversation.", "Nog niet vastgesteld; verduidelijk dit in het gesprek.", "Noch nicht festgestellt; im Gespräch klären.", "Pas encore établi ; à préciser dans la conversation.", "Aún no establecido; acláralo en la conversación."],
            "approveUnavailable": ["Approval is not available for this definition yet.", "Goedkeuring is nog niet beschikbaar voor deze definitie.", "Die Genehmigung dieser Definition ist noch nicht verfügbar.", "L’approbation de cette définition n’est pas encore disponible.", "La aprobación de esta definición aún no está disponible."],
            "proposed": ["Suggested dependency", "Voorgestelde afhankelijkheid", "Vorgeschlagene Abhängigkeit", "Dépendance proposée", "Dependencia propuesta"],
            "established": ["Established dependency", "Vastgelegde afhankelijkheid", "Festgelegte Abhängigkeit", "Dépendance établie", "Dependencia establecida"],
            "BOUNDED_REPOSITORY_CHANGE": ["Bounded repository changes", "Begrensde repositorywijzigingen", "Begrenzte Repositoryänderungen", "Modifications limitées du dépôt", "Cambios limitados del repositorio"],
            "READ_ONLY_ASSESSMENT": ["Read-only investigation", "Onderzoek zonder wijzigingen", "Untersuchung ohne Änderungen", "Analyse sans modifications", "Investigación sin cambios"],
            "DOCUMENTATION_ONLY": ["Documentation changes only", "Alleen documentatiewijzigingen", "Nur Dokumentationsänderungen", "Modifications de documentation seulement", "Solo cambios de documentación"],
            "ARCHITECTURE_DESIGN_ONLY": ["Design work only", "Alleen ontwerpwerk", "Nur Entwurfsarbeit", "Conception seulement", "Solo diseño"],
            "GIT": ["Changes stay within the shown repository scope", "Wijzigingen blijven binnen de getoonde repositoryscope", "Änderungen bleiben im angezeigten Repositoryumfang", "Les modifications restent dans le périmètre du dépôt affiché", "Los cambios permanecen dentro del alcance mostrado"],
            "EVIDENCE_ONLY": ["Evidence without repository changes", "Bewijs zonder repositorywijzigingen", "Nachweise ohne Repositoryänderungen", "Preuves sans modifications du dépôt", "Evidencias sin cambios del repositorio"],
            "APPROVED_WAITING": ["Approved — waiting for release", "Goedgekeurd — wacht op vrijgave", "Genehmigt — wartet auf Freigabe", "Approuvé — en attente de libération", "Aprobado — esperando liberación"],
            "SUPERSEDED": ["A newer draft needs its own approval", "Een nieuwer concept heeft eigen goedkeuring nodig", "Ein neuerer Entwurf benötigt eine eigene Genehmigung", "Un nouveau brouillon nécessite sa propre approbation", "Un borrador nuevo requiere su propia aprobación"],
            "concepts": ["Draft missions", "Conceptmissies", "Missionsentwürfe", "Missions en brouillon", "Misiones en borrador"],
            "denied": ["You do not have access to these missions.", "Je hebt geen toegang tot deze missies.", "Sie haben keinen Zugriff auf diese Missionen.", "Vous n’avez pas accès à ces missions.", "No tienes acceso a estas misiones."],
            "pending": ["The outcome is not confirmed. Check the original request.", "De uitkomst is niet bevestigd. Controleer het oorspronkelijke verzoek.", "Das Ergebnis ist nicht bestätigt. Prüfen Sie die ursprüngliche Anfrage.", "Le résultat n’est pas confirmé. Vérifiez la demande d’origine.", "El resultado no está confirmado. Comprueba la solicitud original."],
            "resume": ["Check or resume original request", "Oorspronkelijk verzoek controleren of hervatten", "Ursprüngliche Anfrage prüfen oder fortsetzen", "Vérifier ou reprendre la demande d’origine", "Comprobar o reanudar solicitud original"],
            "refresh": ["Refresh", "Vernieuwen", "Aktualisieren", "Actualiser", "Actualizar"],
            "stale": ["The definition or context changed. Refresh before continuing.", "De definitie of context is gewijzigd. Vernieuw vóór doorgaan.", "Die Definition oder der Kontext hat sich geändert. Vor dem Fortfahren aktualisieren.", "La définition ou le contexte a changé. Actualisez avant de continuer.", "La definición o el contexto cambió. Actualiza antes de continuar."],
            "invalid": ["The service response could not be verified.", "Het antwoord van de dienst kon niet worden geverifieerd.", "Die Dienstantwort konnte nicht verifiziert werden.", "La réponse du service n’a pas pu être vérifiée.", "No se pudo verificar la respuesta del servicio."],
            "budget": ["The current allowance is exhausted.", "De huidige limiet is verbruikt.", "Das aktuelle Kontingent ist ausgeschöpft.", "Le quota actuel est épuisé.", "Se agotó el límite actual."],
            "failed": ["This refinement did not complete.", "Deze verfijning is niet voltooid.", "Diese Verfeinerung wurde nicht abgeschlossen.", "Cette précision n’a pas été terminée.", "Esta precisión no se completó."],
            "missions": ["Missions", "Missies", "Missionen", "Missions", "Misiones"],
            "settings": ["Settings", "Instellingen", "Einstellungen", "Réglages", "Ajustes"],
            "panel": ["Workspace panels", "Werkpanelen", "Arbeitsbereiche", "Panneaux", "Paneles"],
            "overview": ["Overview", "Overzicht", "Übersicht", "Vue générale", "Resumen"],
            "chat": ["Conversation", "Gesprek", "Gespräch", "Conversation", "Conversación"],
            "definition": ["Mission definition", "Missiedefinitie", "Missionsdefinition", "Définition de mission", "Definición de misión"],
            "search": ["Find a mission", "Zoek een missie", "Mission suchen", "Rechercher une mission", "Buscar una misión"],
            "display": ["View", "Weergave", "Ansicht", "Affichage", "Vista"],
            "list": ["List", "Lijst", "Liste", "Liste", "Lista"],
            "dependencies": ["Dependencies", "Afhankelijkheden", "Abhängigkeiten", "Dépendances", "Dependencias"],
            "outcomes": ["Intended results", "Beoogde resultaten", "Geplante Ergebnisse", "Résultats attendus", "Resultados previstos"],
            "partial": ["More authorized results may be available.", "Meer toegankelijke resultaten kunnen beschikbaar zijn.", "Weitere berechtigte Ergebnisse sind möglicherweise verfügbar.", "D’autres résultats autorisés peuvent être disponibles.", "Puede haber más resultados autorizados."],
            "empty": ["Start with your goal", "Begin met je doel", "Beginnen Sie mit Ihrem Ziel", "Commencez par votre objectif", "Empieza con tu objetivo"],
            "connection": ["Connect the qualified mission service in Settings.", "Verbind de gekwalificeerde missiedienst in Instellingen.", "Verbinden Sie den qualifizierten Missionsdienst in den Einstellungen.", "Connectez le service de missions qualifié dans les réglages.", "Conecta el servicio de misiones calificado en Ajustes."],
            "lens": ["Perspective", "Invalshoek", "Perspektive", "Perspective", "Perspectiva"],
            "business": ["Business", "Business", "Business", "Business", "Negocio"],
            "architect": ["Architect", "Architect", "Architekt", "Architecte", "Arquitecto"],
            "prompt": ["What would you like to achieve? Refine the scope together.", "Wat wil je bereiken? Verfijn samen de scope.", "Was möchten Sie erreichen? Verfeinern Sie gemeinsam den Umfang.", "Que souhaitez-vous accomplir ? Précisez ensemble le périmètre.", "¿Qué quieres lograr? Define el alcance en la conversación."],
            "message": ["Your message", "Je bericht", "Ihre Nachricht", "Votre message", "Tu mensaje"],
            "send": ["Send and refine", "Versturen en verfijnen", "Senden und verfeinern", "Envoyer et préciser", "Enviar y precisar"],
            "value": ["Goal and value", "Doel en waarde", "Ziel und Nutzen", "Objectif et valeur", "Objetivo y valor"],
            "scope": ["Within scope", "Binnen scope", "Im Umfang", "Dans le périmètre", "Dentro del alcance"],
            "excluded": ["Outside scope", "Buiten scope", "Außerhalb des Umfangs", "Hors périmètre", "Fuera del alcance"],
            "done": ["When it is done", "Wanneer het klaar is", "Wann es fertig ist", "Quand ce sera terminé", "Cuándo estará terminado"],
            "questions": ["Open questions", "Open vragen", "Offene Fragen", "Questions ouvertes", "Preguntas abiertas"],
            "changes": ["What changed", "Wat is gewijzigd", "Was sich geändert hat", "Ce qui a changé", "Qué cambió"],
            "approve": ["Approve and prepare", "Goedkeuren en klaarzetten", "Genehmigen und vorbereiten", "Approuver et préparer", "Aprobar y preparar"],
            "approvalEffect": ["Approve this exact definition. Execution starts through its existing authorized route.", "Keur deze exacte definitie goed. Uitvoering start via de bestaande bevoegde route.", "Genehmigen Sie diese genaue Definition. Die Ausführung beginnt über den bestehenden berechtigten Weg.", "Approuvez cette définition exacte. L’exécution suit son parcours autorisé existant.", "Aprueba esta definición exacta. La ejecución sigue su ruta autorizada existente."],
            "inspector": ["Technical details", "Technische details", "Technische Details", "Détails techniques", "Detalles técnicos"],
            "revision": ["Version", "Versie", "Version", "Version", "Versión"],
            "choose": ["Choose a mission to see its definition.", "Kies een missie om de definitie te zien.", "Wählen Sie eine Mission für ihre Definition.", "Choisissez une mission pour voir sa définition.", "Elige una misión para ver su definición."],
            "zoomOut": ["Zoom out", "Uitzoomen", "Verkleinern", "Dézoomer", "Alejar"],
            "zoomIn": ["Zoom in", "Inzoomen", "Vergrößern", "Zoomer", "Acercar"],
            "focus": ["Focus selection", "Selectie in beeld", "Auswahl fokussieren", "Centrer la sélection", "Centrar selección"],
            "fit": ["Fit", "Passend maken", "Einpassen", "Ajuster", "Ajustar"],
            "edgeLegend": ["Arrows mean requires. Dashed: suggested. Solid: established.", "Pijlen betekenen vereist. Stippellijn: voorgesteld. Doorgetrokken lijn: vastgelegd.", "Pfeile bedeuten benötigt. Gestrichelt: vorgeschlagen. Durchgezogen: festgelegt.", "Les flèches indiquent un prérequis. Pointillé : proposé. Continu : établi.", "Las flechas indican requisitos. Discontinua: propuesta. Continua: establecida."],
            "CONCEPT": ["Draft", "Concept", "Entwurf", "Brouillon", "Borrador"],
            "REFINEMENT_REQUIRED": ["Needs refinement", "Te verfijnen", "Zu verfeinern", "À préciser", "Por precisar"],
            "AWAITING_APPROVAL": ["Ready for approval", "Klaar voor goedkeuring", "Bereit zur Genehmigung", "Prêt à approuver", "Listo para aprobar"],
        ]
        return rows[key]?[index] ?? key
    }
}
