import Foundation

enum MissionWorkspaceCopy {
    static func text(_ key: String, language: String) -> String {
        let index = ["en": 0, "nl": 1, "de": 2, "fr": 3, "es": 4][language] ?? 0
        let rows: [String: [String]] = [
            "statusFilter": ["Status", "Status", "Status", "État", "Estado"],
            "allStatuses": ["All statuses", "Alle statussen", "Alle Zustände", "Tous les états", "Todos los estados"],
            "USER": ["You", "Jij", "Sie", "Vous", "Tú"],
            "BUSINESS": ["Business", "Business", "Business", "Business", "Negocio"],
            "ARCHITECTURE": ["Architect", "Architect", "Architekt", "Architecte", "Arquitecto"],
            "Research": ["Research", "Onderzoek", "Untersuchung", "Recherche", "Investigación"],
            "objective": ["Goal", "Doel", "Ziel", "Objectif", "Objetivo"],
            "architectureChoices": ["Design choices", "Ontwerpkeuzes", "Entwurfsentscheidungen", "Choix de conception", "Decisiones de diseño"],
            "consequences": ["What approval allows", "Wat goedkeuring toestaat", "Was die Genehmigung erlaubt", "Ce que l’approbation permet", "Qué permite la aprobación"],
            "risks": ["Risks to consider", "Risico’s om te beoordelen", "Zu beurteilende Risiken", "Risques à évaluer", "Riesgos a evaluar"],
            "remainingDecisions": ["Remaining human decisions", "Resterende menselijke beslissingen", "Verbleibende menschliche Entscheidungen", "Décisions humaines restantes", "Decisiones humanas pendientes"],
            "notEstablished": ["Not established yet; clarify in the conversation.", "Nog niet vastgesteld; verduidelijk dit in het gesprek.", "Noch nicht festgestellt; im Gespräch klären.", "Pas encore établi ; à préciser dans la conversation.", "Aún no establecido; acláralo en la conversación."],
            "approveUnavailable": ["Approval is not available for this definition yet.", "Goedkeuring is nog niet beschikbaar voor deze definitie.", "Die Genehmigung dieser Definition ist noch nicht verfügbar.", "L’approbation de cette définition n’est pas encore disponible.", "La aprobación de esta definición aún no está disponible."],
            "proposed": ["Suggested dependency", "Voorgestelde afhankelijkheid", "Vorgeschlagene Abhängigkeit", "Dépendance proposée", "Dependencia propuesta"],
            "established": ["Dependency in approved definition", "Afhankelijkheid in goedgekeurde definitie", "Abhängigkeit im genehmigten Entwurf", "Dépendance dans la définition approuvée", "Dependencia en la definición aprobada"],
            "BOUNDED_REPOSITORY_CHANGE": ["Bounded repository changes", "Begrensde repositorywijzigingen", "Begrenzte Repositoryänderungen", "Modifications limitées du dépôt", "Cambios limitados del repositorio"],
            "READ_ONLY_ASSESSMENT": ["Read-only investigation", "Onderzoek zonder wijzigingen", "Untersuchung ohne Änderungen", "Analyse sans modifications", "Investigación sin cambios"],
            "DOCUMENTATION_ONLY": ["Documentation changes only", "Alleen documentatiewijzigingen", "Nur Dokumentationsänderungen", "Modifications de documentation seulement", "Solo cambios de documentación"],
            "ARCHITECTURE_DESIGN_ONLY": ["Design work only", "Alleen ontwerpwerk", "Nur Entwurfsarbeit", "Conception seulement", "Solo diseño"],
            "GIT": ["Changes stay within the shown repository scope", "Wijzigingen blijven binnen de getoonde repositoryscope", "Änderungen bleiben im angezeigten Repositoryumfang", "Les modifications restent dans le périmètre du dépôt affiché", "Los cambios permanecen dentro del alcance mostrado"],
            "EVIDENCE_ONLY": ["Evidence without repository changes", "Bewijs zonder repositorywijzigingen", "Nachweise ohne Repositoryänderungen", "Preuves sans modifications du dépôt", "Evidencias sin cambios del repositorio"],
            "READY_FOR_GOVERNED_ACTIVATION": ["Ready for controlled activation", "Klaar voor gecontroleerde activering", "Bereit zur kontrollierten Aktivierung", "Prêt pour l’activation contrôlée", "Listo para la activación controlada"],
            "SUBJECT_STALE": ["The recorded subject needs a new review", "Het vastgelegde voorstel vereist een nieuwe beoordeling", "Der gespeicherte Vorschlag benötigt eine neue Prüfung", "Le sujet enregistré nécessite un nouvel examen", "El asunto registrado necesita una nueva revisión"],
            "RECOMMENDED": ["Proposed for review", "Voorgesteld ter beoordeling", "Zur Prüfung vorgeschlagen", "Proposé pour examen", "Propuesto para revisión"],
            "BUSINESS_APPROVED": ["Business review recorded", "Zakelijke beoordeling vastgelegd", "Geschäftliche Prüfung erfasst", "Examen métier enregistré", "Revisión empresarial registrada"],
            "canonicalHistory": ["Recorded approvals", "Vastgelegde goedkeuringen", "Gespeicherte Genehmigungen", "Approbations enregistrées", "Aprobaciones registradas"],
            "recordedVersion": ["Definition version", "Definitieversie", "Definitionsversion", "Version de définition", "Versión de definición"],
            "olderApproval": ["This approval belongs to the older definition", "Deze goedkeuring hoort bij de eerdere definitie", "Diese Genehmigung gehört zur älteren Definition", "Cette approbation concerne l’ancienne définition", "Esta aprobación pertenece a la definición anterior"],
            "executionStatus": ["Execution conditions", "Uitvoeringsvoorwaarden", "Ausführungsbedingungen", "Conditions d’exécution", "Condiciones de ejecución"],
            "executionUnobserved": ["Actual execution resources have not been observed; physical execution is not proven ready.", "Werkelijke uitvoeringsmiddelen zijn niet waargenomen; fysieke uitvoering is niet bewezen gereed.", "Reale Ausführungsressourcen wurden nicht beobachtet; physische Ausführung ist nicht nachweislich bereit.", "Les ressources d’exécution réelles n’ont pas été observées ; l’exécution physique n’est pas prouvée prête.", "No se han observado recursos de ejecución reales; no se ha probado que la ejecución física esté preparada."],
            "Investigation": ["Investigation", "Onderzoek", "Untersuchung", "Investigation", "Investigación"],
            "Architecture": ["Architecture", "Architectuur", "Architektur", "Architecture", "Arquitectura"],
            "Implementation": ["Implementation", "Implementatie", "Implementierung", "Implémentation", "Implementación"],
            "Documentation": ["Documentation", "Documentatie", "Dokumentation", "Documentation", "Documentación"],
            "Needs clarification": ["Needs clarification", "Te verduidelijken", "Klärung erforderlich", "À clarifier", "Necesita aclaración"],
            "components": ["Affected components", "Betrokken onderdelen", "Betroffene Komponenten", "Composants concernés", "Componentes afectados"],
            "suggestedResults": ["Suggested separate results", "Voorgestelde afzonderlijke resultaten", "Vorgeschlagene separate Ergebnisse", "Résultats distincts proposés", "Resultados independientes propuestos"],
            "suggestedOnly": ["Suggestion; no separate mission has been registered or approved.", "Voorstel; er is geen aparte missie geregistreerd of goedgekeurd.", "Vorschlag; keine separate Mission wurde registriert oder genehmigt.", "Proposition ; aucune mission distincte n’est enregistrée ou approuvée.", "Propuesta; no se ha registrado ni aprobado una misión independiente."],
            "separateSuggestion": ["Refine as a separate mission", "Verfijnen als aparte missie", "Als separate Mission verfeinern", "Affiner comme mission distincte", "Refinar como misión independiente"],
            "separatePrompt": ["I want to refine this as a separate mission:", "Ik wil dit als aparte missie verfijnen:", "Ich möchte dies als separate Mission verfeinern:", "Je souhaite affiner ceci comme mission distincte :", "Quiero refinar esto como una misión independiente:"],
            "current": ["Mission service connected", "Missiedienst verbonden", "Missionsdienst verbunden", "Service de missions connecté", "Servicio de misiones conectado"],
            "setupTitle": ["Mission service", "Missiedienst", "Missionsdienst", "Service de missions", "Servicio de misiones"],
            "setupOnce": ["Configure scoped access once. Ordinary missions use chat and do not request new permissions.", "Stel begrensde toegang eenmaal in. Normale missies verlopen via chat en vragen geen nieuwe rechten.", "Richten Sie den begrenzten Zugang einmal ein. Normale Missionen verwenden den Chat ohne neue Rechte.", "Configurez une fois l’accès limité. Les missions ordinaires passent par le chat sans nouvelles permissions.", "Configure una vez el acceso limitado. Las misiones normales usan el chat sin nuevos permisos."],
            "setupAccess": ["Owner-provided mission access", "Door beheer verstrekte missietoegang", "Vom Betreiber bereitgestellter Missionszugang", "Accès aux missions fourni par l’administrateur", "Acceso a misiones proporcionado por el administrador"],
            "setupSave": ["Save and check access", "Toegang opslaan en controleren", "Zugang speichern und prüfen", "Enregistrer et vérifier l’accès", "Guardar y verificar el acceso"],
            "newMission": ["New mission", "Nieuwe missie", "Neue Mission", "Nouvelle mission", "Nueva misión"],
            "blockers": ["Still required", "Nog nodig", "Noch erforderlich", "Encore requis", "Aún requerido"],
            "DEPENDENCY_NOT_PROVEN": ["A required predecessor has not been proven complete.", "Een vereiste voorganger is nog niet bewezen voltooid.", "Ein erforderlicher Vorgänger ist noch nicht nachweislich abgeschlossen.", "Un prérequis n’est pas encore prouvé terminé.", "No se ha demostrado que un requisito previo esté completo."],
            "EXPLICIT_WORKSET_RELEASE_REQUIRED": ["The approved work still needs explicit release.", "Het goedgekeurde werk moet nog expliciet worden vrijgegeven.", "Die genehmigte Arbeit benötigt noch eine ausdrückliche Freigabe.", "Le travail approuvé nécessite encore une libération explicite.", "El trabajo aprobado aún requiere liberación explícita."],
            "ACTIVATION_INPUTS_UNAVAILABLE": ["Required execution conditions are not available yet.", "Vereiste uitvoeringsvoorwaarden zijn nog niet beschikbaar.", "Erforderliche Ausführungsbedingungen sind noch nicht verfügbar.", "Les conditions d’exécution requises ne sont pas encore disponibles.", "Las condiciones de ejecución necesarias aún no están disponibles."],
            "WORKSET_HELD": ["The work is on hold.", "Het werk staat in de wachtstand.", "Die Arbeit ist angehalten.", "Le travail est en attente.", "El trabajo está en espera."],
            "anotherCondition": ["Another required condition is not satisfied yet.", "Een andere vereiste voorwaarde is nog niet vervuld.", "Eine weitere erforderliche Bedingung ist noch nicht erfüllt.", "Une autre condition requise n’est pas encore remplie.", "Aún no se cumple otra condición necesaria."],
            "APPROVED_WAITING": ["Approved — waiting for release", "Goedgekeurd — wacht op vrijgave", "Genehmigt — wartet auf Freigabe", "Approuvé — en attente de libération", "Aprobado — esperando liberación"],
            "SUPERSEDED": ["A newer draft needs its own approval", "Een nieuwer concept heeft eigen goedkeuring nodig", "Ein neuerer Entwurf benötigt eine eigene Genehmigung", "Un nouveau brouillon nécessite sa propre approbation", "Un borrador nuevo requiere su propia aprobación"],
            "concepts": ["Draft missions", "Conceptmissies", "Missionsentwürfe", "Missions en brouillon", "Misiones en borrador"],
            "denied": ["You do not have access to these missions.", "Je hebt geen toegang tot deze missies.", "Sie haben keinen Zugriff auf diese Missionen.", "Vous n’avez pas accès à ces missions.", "No tienes acceso a estas misiones."],
            "pending": ["The outcome is not confirmed. Check the original request.", "De uitkomst is niet bevestigd. Controleer het oorspronkelijke verzoek.", "Das Ergebnis ist nicht bestätigt. Prüfen Sie die ursprüngliche Anfrage.", "Le résultat n’est pas confirmé. Vérifiez la demande d’origine.", "El resultado no está confirmado. Comprueba la solicitud original."],
            "resume": ["Check or resume original request", "Oorspronkelijk verzoek controleren of hervatten", "Ursprüngliche Anfrage prüfen oder fortsetzen", "Vérifier ou reprendre la demande d’origine", "Comprobar o reanudar solicitud original"],
            "refresh": ["Refresh", "Vernieuwen", "Aktualisieren", "Actualiser", "Actualizar"],
            "stale": ["The definition or context changed. Refresh before continuing.", "De definitie of context is gewijzigd. Vernieuw vóór doorgaan.", "Die Definition oder der Kontext hat sich geändert. Vor dem Fortfahren aktualisieren.", "La définition ou le contexte a changé. Actualisez avant de continuer.", "La definición o el contexto cambió. Actualiza antes de continuar."],
            "invalid": ["The service response could not be verified.", "Het antwoord van de dienst kon niet worden geverifieerd.", "Die Dienstantwort konnte nicht verifiziert werden.", "La réponse du service n’a pas pu être vérifiée.", "No se pudo verificar la respuesta del servicio."],
            "budget": ["The current allowance is exhausted.", "De huidige limiet is verbruikt.", "Das aktuelle Kontingent ist ausgeschöpft.", "Le quota actuel est épuisé.", "Se agotó el límite actual."],
            "failed": ["This refinement did not complete.", "Deze verfijning is niet voltooid.", "Diese Verfeinerung wurde nicht abgeschlossen.", "Cette précision n’a pas été terminée.", "Esta precisión no se completó."],
            "missions": ["Missions", "Missies", "Missionen", "Missions", "Misiones"],
            "settings": ["Settings", "Instellingen", "Einstellungen", "Réglages", "Ajustes"],
            "panel": ["Workspace panels", "Werkpanelen", "Arbeitsbereiche", "Panneaux", "Paneles"],
            "overview": ["Overview", "Overzicht", "Übersicht", "Vue générale", "Resumen"],
            "chat": ["Conversation", "Gesprek", "Gespräch", "Conversation", "Conversación"],
            "definition": ["Mission definition", "Missiedefinitie", "Missionsdefinition", "Définition de mission", "Definición de misión"],
            "search": ["Find a mission", "Zoek een missie", "Mission suchen", "Rechercher une mission", "Buscar una misión"],
            "display": ["View", "Weergave", "Ansicht", "Affichage", "Vista"],
            "list": ["List", "Lijst", "Liste", "Liste", "Lista"],
            "dependencies": ["Dependencies", "Afhankelijkheden", "Abhängigkeiten", "Dépendances", "Dependencias"],
            "outcomes": ["Intended results", "Beoogde resultaten", "Geplante Ergebnisse", "Résultats attendus", "Resultados previstos"],
            "partial": ["More authorized results may be available.", "Meer toegankelijke resultaten kunnen beschikbaar zijn.", "Weitere berechtigte Ergebnisse sind möglicherweise verfügbar.", "D’autres résultats autorisés peuvent être disponibles.", "Puede haber más resultados autorizados."],
            "empty": ["Start with your goal", "Begin met je doel", "Beginnen Sie mit Ihrem Ziel", "Commencez par votre objectif", "Empieza con tu objetivo"],
            "connection": ["Connect the qualified mission service in Settings.", "Verbind de gekwalificeerde missiedienst in Instellingen.", "Verbinden Sie den qualifizierten Missionsdienst in den Einstellungen.", "Connectez le service de missions qualifié dans les réglages.", "Conecta el servicio de misiones calificado en Ajustes."],
            "lens": ["Perspective", "Invalshoek", "Perspektive", "Perspective", "Perspectiva"],
            "business": ["Business", "Business", "Business", "Business", "Negocio"],
            "architect": ["Architect", "Architect", "Architekt", "Architecte", "Arquitecto"],
            "prompt": ["What would you like to achieve? Refine the scope together.", "Wat wil je bereiken? Verfijn samen de scope.", "Was möchten Sie erreichen? Verfeinern Sie gemeinsam den Umfang.", "Que souhaitez-vous accomplir ? Précisez ensemble le périmètre.", "¿Qué quieres lograr? Define el alcance en la conversación."],
            "message": ["Your message", "Je bericht", "Ihre Nachricht", "Votre message", "Tu mensaje"],
            "send": ["Send and refine", "Versturen en verfijnen", "Senden und verfeinern", "Envoyer et préciser", "Enviar y precisar"],
            "value": ["Goal and value", "Doel en waarde", "Ziel und Nutzen", "Objectif et valeur", "Objetivo y valor"],
            "scope": ["Within scope", "Binnen scope", "Im Umfang", "Dans le périmètre", "Dentro del alcance"],
            "excluded": ["Outside scope", "Buiten scope", "Außerhalb des Umfangs", "Hors périmètre", "Fuera del alcance"],
            "done": ["When it is done", "Wanneer het klaar is", "Wann es fertig ist", "Quand ce sera terminé", "Cuándo estará terminado"],
            "questions": ["Open questions", "Open vragen", "Offene Fragen", "Questions ouvertes", "Preguntas abiertas"],
            "changes": ["What changed", "Wat is gewijzigd", "Was sich geändert hat", "Ce qui a changé", "Qué cambió"],
            "approve": ["Approve and prepare", "Goedkeuren en klaarzetten", "Genehmigen und vorbereiten", "Approuver et préparer", "Aprobar y preparar"],
            "approvalEffect": ["Approve this exact definition. Execution starts through its existing authorized route.", "Keur deze exacte definitie goed. Uitvoering start via de bestaande bevoegde route.", "Genehmigen Sie diese genaue Definition. Die Ausführung beginnt über den bestehenden berechtigten Weg.", "Approuvez cette définition exacte. L’exécution suit son parcours autorisé existant.", "Aprueba esta definición exacta. La ejecución sigue su ruta autorizada existente."],
            "inspector": ["Technical details", "Technische details", "Technische Details", "Détails techniques", "Detalles técnicos"],
            "revision": ["Version", "Versie", "Version", "Version", "Versión"],
            "choose": ["Choose a mission to see its definition.", "Kies een missie om de definitie te zien.", "Wählen Sie eine Mission für ihre Definition.", "Choisissez une mission pour voir sa définition.", "Elige una misión para ver su definición."],
            "zoomOut": ["Zoom out", "Uitzoomen", "Verkleinern", "Dézoomer", "Alejar"],
            "zoomIn": ["Zoom in", "Inzoomen", "Vergrößern", "Zoomer", "Acercar"],
            "focus": ["Focus selection", "Selectie in beeld", "Auswahl fokussieren", "Centrer la sélection", "Centrar selección"],
            "fit": ["Fit", "Passend maken", "Einpassen", "Ajuster", "Ajustar"],
            "edgeLegend": ["Arrows mean requires. Dashed: proposed. Solid: in approved definition; execution order is not released.", "Pijlen betekenen vereist. Stippellijn: voorgesteld. Doorgetrokken: in goedgekeurde definitie; uitvoeringsvolgorde is niet vrijgegeven.", "Pfeile bedeuten benötigt. Gestrichelt: vorgeschlagen. Durchgezogen: im genehmigten Entwurf; Ausführungsreihenfolge nicht freigegeben.", "Les flèches indiquent un prérequis. Pointillé : proposé. Continu : dans la définition approuvée ; ordre d’exécution non libéré.", "Las flechas indican requisitos. Discontinua: propuesta. Continua: en la definición aprobada; orden de ejecución no liberado."],
            "CONCEPT": ["Draft", "Concept", "Entwurf", "Brouillon", "Borrador"],
            "REFINEMENT_REQUIRED": ["Needs refinement", "Te verfijnen", "Zu verfeinern", "À préciser", "Por precisar"],
            "AWAITING_APPROVAL": ["Ready for approval", "Klaar voor goedkeuring", "Bereit zur Genehmigung", "Prêt à approuver", "Listo para aprobar"],
        ]
        return rows[key]?[index] ?? key
    }
    static func blocker(_ code:String,language:String)->String {
        let key=code=="NOT_RELEASED" ? "EXPLICIT_WORKSET_RELEASE_REQUIRED":code
        let known=["DEPENDENCY_NOT_PROVEN","EXPLICIT_WORKSET_RELEASE_REQUIRED","ACTIVATION_INPUTS_UNAVAILABLE","WORKSET_HELD"]
        return text(known.contains(key) ? key:"anotherCondition",language:language)
    }

}
