import Foundation

enum WorksetReleaseCopy {
    static let languages = ["en", "nl", "de", "fr", "es"]
    static let entries: [String: [String]] = [
        "setup": ["Execution permission — owner setup", "Uitvoeringsbevoegdheid — beheer", "Ausführungsberechtigung — Einrichtung", "Autorisation d’exécution — administration", "Permiso de ejecución — administración"],
        "setupHint": ["An owner first supplies a separate, finite project permission. Pairing verifies its current scope and stores it privately on this Mac. It grants no extra rights.", "Een beheerder verstrekt eerst een afzonderlijke, eindige projectbevoegdheid. Koppelen controleert de actuele scope en bewaart deze privé op deze Mac. Het geeft geen extra rechten.", "Ein Verantwortlicher stellt zuerst eine separate, begrenzte Projektberechtigung bereit. Die Kopplung prüft den aktuellen Bereich und speichert sie privat auf diesem Mac. Sie gewährt keine zusätzlichen Rechte.", "Un responsable fournit d’abord une autorisation de projet distincte et limitée. L’association vérifie sa portée actuelle et la conserve en privé sur ce Mac. Elle ne donne aucun droit supplémentaire.", "Un administrador proporciona primero un permiso de proyecto independiente y limitado. La vinculación verifica su alcance actual y lo guarda de forma privada en este Mac. No concede derechos adicionales."],
        "setupToken": ["Owner-supplied permission", "Door beheerder verstrekte bevoegdheid", "Vom Verantwortlichen bereitgestellte Berechtigung", "Autorisation fournie par le responsable", "Permiso proporcionado por el administrador"],
        "pair": ["Verify and pair", "Controleren en koppelen", "Prüfen und koppeln", "Vérifier et associer", "Verificar y vincular"],
        "forget": ["Forget this permission", "Deze bevoegdheid vergeten", "Diese Berechtigung vergessen", "Oublier cette autorisation", "Olvidar este permiso"],
        "active": ["Active according to Forge", "Actief volgens Forge", "Laut Forge aktiv", "Actif selon Forge", "Activo según Forge"],
        "completed": ["Completed according to Forge", "Afgerond volgens Forge", "Laut Forge abgeschlossen", "Terminé selon Forge", "Completado según Forge"],
        "originalRelease": ["Original release", "Oorspronkelijke vrijgave", "Ursprüngliche Freigabe", "Autorisation initiale", "Autorización original"],
        "withdrawal": ["Withdrawal", "Terugname", "Rücknahme", "Retrait", "Retirada"],
        "originalConfirmed": ["This original release was recorded. Its current state appears below.", "Deze oorspronkelijke vrijgave is vastgelegd. De actuele toestand staat hieronder.", "Diese ursprüngliche Freigabe wurde erfasst. Der aktuelle Zustand erscheint unten.", "Cette autorisation initiale a été enregistrée. Son état actuel apparaît ci-dessous.", "Esta autorización original se registró. Su estado actual aparece abajo."],
        "withdrawalConfirmed": ["This future-only withdrawal was recorded. Ongoing work was not cancelled.", "Deze terugname voor toekomstige starts is vastgelegd. Lopend werk is niet geannuleerd.", "Diese Rücknahme künftiger Starts wurde erfasst. Laufende Arbeit wurde nicht abgebrochen.", "Ce retrait des démarrages futurs a été enregistré. Le travail en cours n’a pas été annulé.", "Esta retirada de inicios futuros se registró. El trabajo en curso no se canceló."],
        "list": ["Execution list", "Uitvoeringslijst", "Ausführungsliste", "Liste d’exécution", "Lista de ejecución"],
        "include": ["Add to execution list", "Toevoegen aan uitvoeringslijst", "Zur Ausführungsliste hinzufügen", "Ajouter à la liste d’exécution", "Añadir a la lista de ejecución"],
        "remove": ["Remove from execution list", "Verwijderen uit uitvoeringslijst", "Aus der Ausführungsliste entfernen", "Retirer de la liste d’exécution", "Quitar de la lista de ejecución"],
        "preview": ["Preview selection", "Selectie bekijken", "Auswahl ansehen", "Voir la sélection", "Ver selección"],
        "release": ["Release for execution", "Vrijgeven voor uitvoering", "Zur Ausführung freigeben", "Autoriser l’exécution", "Autorizar ejecución"],
        "disarm": ["Withdraw future starts", "Toekomstige starts terugnemen", "Künftige Starts zurücknehmen", "Retirer les démarrages futurs", "Retirar inicios futuros"],
        "boundary": ["This authorizes future starts only. Ongoing work is not cancelled or reversed.", "Dit geeft alleen toestemming voor toekomstige starts. Lopend werk wordt niet geannuleerd of teruggedraaid.", "Dies erlaubt nur künftige Starts. Laufende Arbeit wird weder abgebrochen noch rückgängig gemacht.", "Cette autorisation concerne uniquement les démarrages futurs. Le travail en cours n’est ni annulé ni inversé.", "Esto solo autoriza inicios futuros. El trabajo en curso no se cancela ni se revierte."],
        "resources": ["Release does not confirm execution. Physical execution resources have not been observed.", "Vrijgave bevestigt geen uitvoering. Fysieke uitvoeringsmiddelen zijn nog niet waargenomen.", "Die Freigabe bestätigt keine Ausführung. Physische Ausführungsressourcen wurden nicht beobachtet.", "L’autorisation ne confirme pas l’exécution. Les ressources physiques n’ont pas été observées.", "La autorización no confirma la ejecución. No se han observado recursos físicos."],
        "content": ["The mission content is already approved. You confirm only this selection, order and finite execution limits.", "De missie-inhoud is al goedgekeurd. Je bevestigt alleen deze selectie, volgorde en eindige uitvoeringsgrenzen.", "Die Missionsinhalte sind bereits genehmigt. Sie bestätigen nur diese Auswahl, Reihenfolge und begrenzten Ausführungsgrenzen.", "Le contenu des missions est déjà approuvé. Vous confirmez uniquement cette sélection, cet ordre et ces limites finies.", "El contenido de las misiones ya está aprobado. Solo confirmas esta selección, orden y límites finitos."],
        "depends": ["Starts only after required final acceptance of", "Start pas na de vereiste finale acceptatie van", "Startet erst nach der erforderlichen endgültigen Abnahme von", "Démarre seulement après l’acceptation finale requise de", "Solo inicia tras la aceptación final necesaria de"],
        "continuous": ["The next eligible mission may start automatically after required acceptance, within these limits.", "De volgende geschikte missie mag na de vereiste acceptatie automatisch starten, binnen deze grenzen.", "Die nächste geeignete Mission darf nach der erforderlichen Abnahme innerhalb dieser Grenzen automatisch starten.", "La prochaine mission éligible peut démarrer automatiquement après l’acceptation requise, dans ces limites.", "La siguiente misión elegible puede iniciar automáticamente tras la aceptación necesaria, dentro de estos límites."],
        "protected-delivery": ["Protected delivery remains required", "Beschermde oplevering blijft vereist", "Geschützte Auslieferung bleibt erforderlich", "La livraison protégée reste requise", "La entrega protegida sigue siendo necesaria"],
        "READ_ONLY_ASSESSMENT": ["Read-only assessment; no repository changes", "Alleen onderzoek; geen repositorywijzigingen", "Nur Untersuchung; keine Repositoryänderungen", "Évaluation en lecture seule ; aucune modification du dépôt", "Evaluación de solo lectura; sin cambios en el repositorio"],
        "BOUNDED_REPOSITORY_CHANGE": ["Only approved source changes; protected delivery remains required", "Alleen goedgekeurde bronwijzigingen; beschermde oplevering blijft vereist", "Nur genehmigte Quelländerungen; geschützte Auslieferung bleibt erforderlich", "Uniquement les changements approuvés ; livraison protégée requise", "Solo cambios de código aprobados; entrega protegida obligatoria"],
        "DOCUMENTATION_ONLY": ["Only approved documentation may change", "Alleen goedgekeurde documentatie mag wijzigen", "Nur genehmigte Dokumentation darf geändert werden", "Seule la documentation approuvée peut être modifiée", "Solo puede cambiar la documentación aprobada"],
        "ARCHITECTURE_DESIGN_ONLY": ["Only the approved architecture design may change", "Alleen het goedgekeurde architectuurontwerp mag wijzigen", "Nur der genehmigte Architekturentwurf darf geändert werden", "Seule la conception d’architecture approuvée peut changer", "Solo puede cambiar el diseño de arquitectura aprobado"],
        "after_action": ["Further action requires the existing continuation decision", "Vervolg vraagt het bestaande vervolgbesluit", "Weitere Schritte erfordern die bestehende Fortsetzungsentscheidung", "La suite exige la décision de continuation existante", "Continuar requiere la decisión de continuación existente"],
        "expiry": ["Valid until", "Geldig tot", "Gültig bis", "Valable jusqu’au", "Válido hasta"],
        "limit": ["Maximum starts", "Maximaal aantal starts", "Maximale Starts", "Nombre maximal de démarrages", "Máximo de inicios"],
        "empty": ["Select approved missions in the tree or graph, then add them from their detail.", "Selecteer goedgekeurde missies in de boom of grafiek en voeg ze vanuit hun detail toe.", "Wählen Sie genehmigte Missionen im Baum oder Diagramm und fügen Sie sie über die Details hinzu.", "Sélectionnez des missions approuvées dans l’arbre ou le graphe, puis ajoutez-les depuis leurs détails.", "Selecciona misiones aprobadas en el árbol o gráfico y añádelas desde sus detalles."],
        "unconfigured": ["Separate execution permission is required.", "Afzonderlijke uitvoeringsbevoegdheid is vereist.", "Eine gesonderte Ausführungsberechtigung ist erforderlich.", "Une autorisation d’exécution distincte est requise.", "Se requiere permiso de ejecución independiente."],
        "denied": ["Execution access has ended. Protected content is hidden.", "De uitvoeringsbevoegdheid is beëindigd. Beschermde inhoud is verborgen.", "Die Ausführungsberechtigung ist beendet. Geschützte Inhalte sind verborgen.", "L’accès d’exécution a pris fin. Le contenu protégé est masqué.", "El acceso de ejecución ha terminado. El contenido protegido está oculto."],
        "unavailable": ["Current status is unavailable. No new release is sent automatically.", "Actuele status is niet beschikbaar. Er wordt niet automatisch opnieuw vrijgegeven.", "Der aktuelle Status ist nicht verfügbar. Es wird keine neue Freigabe automatisch gesendet.", "L’état actuel est indisponible. Aucune nouvelle autorisation n’est envoyée automatiquement.", "El estado actual no está disponible. No se envía otra autorización automáticamente."],
        "pending": ["Original request retained. Refresh follows the same operation.", "Oorspronkelijk verzoek bewaard. Vernieuwen volgt dezelfde operatie.", "Die ursprüngliche Anfrage bleibt erhalten. Aktualisieren folgt demselben Vorgang.", "La demande initiale est conservée. Actualiser suit la même opération.", "La solicitud original se conserva. Actualizar sigue la misma operación."],
        "released": ["Released — execution not yet confirmed", "Vrijgegeven — uitvoering nog niet bevestigd", "Freigegeben — Ausführung noch nicht bestätigt", "Autorisé — exécution non encore confirmée", "Autorizado — ejecución aún no confirmada"],
        "withdrawn": ["Future starts withdrawn", "Toekomstige starts teruggenomen", "Künftige Starts zurückgenommen", "Démarrages futurs retirés", "Inicios futuros retirados"],
        "resume": ["Resume original request", "Oorspronkelijk verzoek hervatten", "Ursprüngliche Anfrage fortsetzen", "Reprendre la demande initiale", "Reanudar solicitud original"],
        "refresh": ["Refresh current status", "Actuele status vernieuwen", "Aktuellen Status aktualisieren", "Actualiser l’état actuel", "Actualizar estado actual"],
        "up": ["Move earlier", "Eerder plaatsen", "Nach vorne verschieben", "Déplacer plus tôt", "Mover antes"],
        "down": ["Move later", "Later plaatsen", "Nach hinten verschieben", "Déplacer plus tard", "Mover después"],
        "newSelection": ["New selection", "Nieuwe selectie", "Neue Auswahl", "Nouvelle sélection", "Nueva selección"],
        "close": ["Close", "Sluiten", "Schließen", "Fermer", "Cerrar"],
        "PREDECESSOR_NOT_SELECTED": ["A required predecessor is missing from your selection.", "Een vereiste voorganger ontbreekt in je selectie.", "Ein erforderlicher Vorgänger fehlt in Ihrer Auswahl.", "Un prédécesseur requis manque dans votre sélection.", "Falta un predecesor necesario en tu selección."],
        "DEPENDENCY_ORDER_CONFLICT": ["A dependency appears after the mission that needs it.", "Een afhankelijkheid staat na de missie die erop wacht.", "Eine Abhängigkeit steht nach der Mission, die sie benötigt.", "Une dépendance apparaît après la mission qui en a besoin.", "Una dependencia aparece después de la misión que la necesita."],
        "DEPENDENCY_SUBJECT_CHANGED": ["The approved dependency revision has changed.", "De goedgekeurde afhankelijkheidsrevisie is gewijzigd.", "Die genehmigte Abhängigkeitsversion hat sich geändert.", "La version approuvée de la dépendance a changé.", "La revisión aprobada de la dependencia ha cambiado."],
        "ANOTHER_WORKSET_ARMED": ["Another execution list is already released.", "Een andere uitvoeringslijst is al vrijgegeven.", "Eine andere Ausführungsliste ist bereits freigegeben.", "Une autre liste d’exécution est déjà autorisée.", "Ya hay otra lista de ejecución autorizada."],
        "SUBJECT_ALREADY_CLAIMED": ["This mission already belongs to an execution list.", "Deze missie hoort al bij een uitvoeringslijst.", "Diese Mission gehört bereits zu einer Ausführungsliste.", "Cette mission appartient déjà à une liste d’exécution.", "Esta misión ya pertenece a una lista de ejecución."],
        "RELEASE_AUTHORITY_UNAVAILABLE": ["Current permission does not allow release.", "De actuele bevoegdheid staat vrijgave niet toe.", "Die aktuelle Berechtigung erlaubt keine Freigabe.", "L’autorisation actuelle ne permet pas l’exécution.", "El permiso actual no permite la autorización."],
        "blocked": ["Release is blocked. Refresh and inspect the current preview.", "Vrijgave is geblokkeerd. Vernieuw en bekijk de actuele voorvertoning.", "Die Freigabe ist blockiert. Aktualisieren Sie die aktuelle Vorschau.", "L’autorisation est bloquée. Actualisez et consultez l’aperçu actuel.", "La autorización está bloqueada. Actualiza y revisa la vista previa actual."]
    ]
    static func text(_ key: String, language: String) -> String {
        let index = languages.firstIndex(of: language) ?? 0
        return entries[key]?[index] ?? MissionWorkspaceCopy.blocker(key, language: language)
    }
}
